
package isilimageprocessing.Dialogues;

import CImage.*;
import CImage.Exceptions.CImageNGException;
import CImage.Observers.JLabelBeanCImage;
import ImageProcessing.NonLineaire.MorphoComplexe;
import java.io.File;
import java.io.IOException;
import javax.swing.JFileChooser;


/**
 *
 * @author  HP_Propri�taire
 */
public class JDialogAfficheMatriceGeoD extends javax.swing.JDialog 
{
    
    private double blanc = 255.0;
    private double noir = 0.0;
    
    
    
    private double   matrice1[][],matrice2[][],matrice3[][];
    private int      M,N;
    private CImageNG image1 ,image2 ,image3 ;
    private int      matrice_int1[][] , matrice_int2[][] ,matrice_int3[][];
    
    private JLabelBeanCImage observer1 , observer2  , observer3;
    
    /** Creates new form JDialogAfficheFourier */
    public JDialogAfficheMatriceGeoD(java.awt.Frame parent, boolean modal,double m[][],String titre) 
    {
        super(parent, modal);
        initComponents();
        setTitle(titre);
        
        matrice1 = m;
        M = matrice1.length;
        N = matrice1[0].length;
        matrice_int1 = new int[M][N];
        matrice_int2 = new int[M][N];
        matrice_int3 = new int[M][N];
        try 
        {
            image1 = new CImageNG(M,N,0);
            image2 = new CImageNG(M,N,0);
            image3 = new CImageNG(M,N,0);
        } 
        catch (CImageNGException ex) 
        { System.out.println("Erreur CImageNG : " + ex.getMessage()); }
        
        observer1 = new JLabelBeanCImage(image1);
        observer2 = new JLabelBeanCImage(image2);
        observer3 = new JLabelBeanCImage(image3);
        jScrollPane1.setViewportView(observer1);
        jScrollPane2.setViewportView(observer2);
        jScrollPane3.setViewportView(observer3);
        
       
        MiseAJourCImage(image1,matrice1,matrice_int1);
        MiseAJourCImage(image2,matrice2,matrice_int2);
        MiseAJourCImage(image3,matrice3,matrice_int3);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane3 = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(75, 150));
        setPreferredSize(new java.awt.Dimension(800, 400));

        jPanel2.setPreferredSize(new java.awt.Dimension(756, 40));

        jButton2.setText("Geodésique");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geodesiqueSimple(evt);
            }
        });

        jButton3.setText("quitter");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Géodésique auto");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                keypressJtextfield1(evt);
            }
        });

        jLabel1.setText("NbIter");

        jButton1.setText("Importer masque");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3)
                    .addComponent(jButton2)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4)))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));
        jPanel1.add(jScrollPane1);
        jPanel1.add(jScrollPane2);
        jPanel1.add(jScrollPane3);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void geodesiqueSimple(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geodesiqueSimple
        
       try{ 
        matrice_int3 =  MorphoComplexe.dilatationGeodesique(  matrice_int1 , matrice_int2, Integer.parseInt(this.jTextField1.getText()));
        for (int i = 0; i < N; i++) {
            for (int j = 0; j < M; j++) {
                 //matrice_int3[i][j] += 120 ; 
                 if(   matrice_int3[i][j] > blanc  )
                         matrice_int3[i][j] = (int) blanc ;
                   if(   matrice_int3[i][j] < noir  )
                         matrice_int3[i][j] = (int) noir ;
            }
        }
        
        image3= new CImageNG(N,M,0);
        image3.setMatrice(matrice_int3);
        observer3.setCImage(image3);
           
       }catch(Exception e){
           System.out.println("e"+e);
       }
        
    }//GEN-LAST:event_geodesiqueSimple

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
          try{ 
        matrice_int3 =  MorphoComplexe.reconstructionGeodesique(matrice_int1, matrice_int2);  
        for (int i = 0; i < N; i++) {
            for (int j = 0; j < M; j++) {
                 //matrice_int3[i][j] += 120 ; 
                 if(   matrice_int3[i][j] > blanc  )
                         matrice_int3[i][j] = (int) blanc ;
                   if(   matrice_int3[i][j] < noir  )
                         matrice_int3[i][j] = (int) noir ;
            }
        }
        
        image3= new CImageNG(N,M,0);
        image3.setMatrice(matrice_int3);
        observer3.setCImage(image3);
           
       }catch(Exception e){
           System.out.println("e"+e);
       }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
             JFileChooser choix = new JFileChooser();
        File fichier;

        choix.setCurrentDirectory(new File("."));
        if (choix.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            fichier = choix.getSelectedFile();
            if (fichier != null) {
                try {
                    image2= new CImageNG(fichier);
                    observer2.setCImage(image2);
                    matrice_int2 = image2.getMatrice();
                    MiseAJourCImage(image2,matrice2,matrice_int2);

                    //activeMenusNG();
                } catch (Exception ex) {
                    System.err.println("Erreur I/O : " + ex.getMessage());
                }
            }
        }
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void keypressJtextfield1(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_keypressJtextfield1
       try{
            Thread.sleep(20);
            Integer.parseInt(this.jTextField1.getText());
        }catch(Exception e){
            System.out.println("invalide"+this.jTextField1.getText());
            this.jTextField1.setText("");
        }
    }//GEN-LAST:event_keypressJtextfield1

    private void MiseAJourCImage(CImageNG img, double[][] mat, int[][] mat_int)
    {
        
        if(img == null || mat == null || mat_int ==null )
            return ;
        
        int val;
        
        for(int i=0 ; i<M ; i++)
            for(int j=0 ; j<N ; j++)
            {     
                
                if (mat[i][j] >= blanc)
                {
                    mat_int[i][j] = 255;
                }
                else
                {
                    if (mat[i][j] <= noir)
                    {
                        mat_int[i][j] = 0;
                    }
                    else
                    {   
                        val = (int)((mat[i][j] - noir)/(blanc-noir)*255+0.5);
                        if (val > 255) val = 255;
                        if (val < 0) val = 0;
                        mat_int[i][j] = val;
                    }
                }
            }
        try 
        {
            img.setMatrice(mat_int);
        } 
        catch (CImageNGException ex) 
        {
            System.out.println("Erreur CImageNG : " + ex.getMessage());
        }
    }
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JDialogAfficheMatriceGeoD(new javax.swing.JFrame(), true,null,null).setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
    
}
